version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: dvops-pro-test/dev-pro-1
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: dvops-pro-test/dev-pro-1