version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: dev-pro-1/scripts/stop_container.sh
      timeout: 300
      runas: dev-pro-1
  AfterInstall:
    - location: dev-pro-1/scripts/start_container.sh
      timeout: 300
      runas: dev-pro-1