version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: dev-pro-1/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: dev-pro-1/start_container.sh
      timeout: 300
      runas: root