FROM python:3.8
# Set the working directory inside the container
WORKDIR /app
# Copy the requirements file

COPY requirements.txt .
# Install the project dependencies
RUN pip install -r requirements.txt
# Copy the application code into the container
COPY . .
# Expose the port the Flask application will be listening on
EXPOSE 8000
# Set environment variables, if necessary
# ENV MY_ENV_VAR=value #####################################nayan test pass ###########################################################3

# Run the Flask application
CMD [ "python", "app.py" ]