version: 0.2

env:
  variables:
    DOCKER_REGISTRY_URL: "your-docker-registry-url"  # Replace with your Docker registry URL
    DOCKER_REGISTRY_USERNAME: "your-username"        # Replace with your Docker registry username
    DOCKER_REGISTRY_PASSWORD: "your-password"        # Replace with your Docker registry password (consider using Secrets Manager)

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing pip"
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r dev-pro-0/dev-pro-1/requirements.txt
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/nayan-flask-python-app:latest dev-pro-0/dev-pro-1
      - echo "Logging in to Docker Hub"
      - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY_URL
  post_build:
    commands:
      - echo "Pushing the Docker image"
      - docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/nayan-flask-python-app:latest
      - echo "Preparing deployment artifacts"
      - mkdir -p dev-pro-0
      - cp dev-pro-0/dev-pro-1/appspec.yml dev-pro-0/appspec.yml
      - cp -r dev-pro-0/dev-pro-1 dev-pro-0/
      - cp -r dev-pro-0/dev-pro-1/scripts dev-pro-0/

artifacts:
  files:
    - dev-pro-0/appspec.yml
    - dev-pro-0/dev-pro-1/**
    - dev-pro-0/dev-pro-1/scripts/**
